"""
Phase 2.2 — Fine-Tune Whisper on Medical Speech Data

Fine-tunes openai/whisper-small on the dataset generated by
generate_medical_speech_data.py.  Produces a model that understands:
  - Drug names, dosages, frequencies
  - Anatomical terms and procedure names
  - Specialist questions across 26 medical domains

Usage (Google Colab T4 / local GPU):
  python notebooks/finetune_whisper_medical.py

Usage (quick CPU smoke-test):
  python notebooks/finetune_whisper_medical.py --smoke-test

After training, update src/voice/stt.py:
  WHISPER_MODEL = "your-hf-username/whisper-medical-panacea"

Required packages (Colab):
  pip install transformers datasets accelerate evaluate jiwer librosa soundfile

Estimated time:
  Google Colab T4 (free) — ~2-3 hours for full dataset
  CPU smoke-test (3 examples) — ~5 min
"""

#  Cell 1: Imports 
# %%
import os
import csv
import json
import math
import librosa
import numpy  as np
from pathlib import Path
from dataclasses import dataclass

import torch
from datasets import Dataset, DatasetDict, Audio
from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
)
import evaluate

print(f"PyTorch  : {torch.__version__}")
print(f"Device   : {'cuda' if torch.cuda.is_available() else 'cpu'}")


#  Cell 2: Config 
# %%
@dataclass
class Config:
    # Paths
    data_dir:    str = "notebooks/data/medical_speech"
    output_dir:  str = "notebooks/whisper_medical_checkpoints"
    hub_model:   str = ""   # Set to "your-hf-username/whisper-medical-panacea" to push

    # Model
    base_model:  str = "openai/whisper-small"
    language:    str = "en"
    task:        str = "transcribe"

    # Training
    max_steps:   int = 4000
    per_device_train_batch_size: int = 16
    per_device_eval_batch_size:  int = 8
    learning_rate: float = 1e-5
    warmup_steps:  int = 500
    fp16:          bool = torch.cuda.is_available()
    save_steps:    int = 1000
    eval_steps:    int = 1000
    logging_steps: int = 25
    gradient_checkpointing: bool = True

    # Smoke test
    smoke_test:  bool = False


cfg = Config()


#  Cell 3: Load and validate metadata 
# %%
def load_metadata(data_dir: str, smoke_test: bool = False) -> tuple[list[dict], list[dict]]:
    """Read metadata.csv and return (train_rows, val_rows)."""
    meta_path = Path(data_dir) / "metadata.csv"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"metadata.csv not found at {meta_path}.\n"
            f"Run: python notebooks/generate_medical_speech_data.py first."
        )

    train_rows, val_rows = [], []
    with open(meta_path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            split   = row["split"]
            wav_rel = row["file"]
            wav_abs = str(Path(data_dir) / split / wav_rel)

            if not Path(wav_abs).exists():
                continue   # audio file missing — skip silently

            entry = {"audio_path": wav_abs, "transcript": row["transcript"]}
            if split == "train":
                train_rows.append(entry)
            else:
                val_rows.append(entry)

    if smoke_test:
        train_rows = train_rows[:6]
        val_rows   = val_rows[:3]

    print(f"Loaded: {len(train_rows):,} train | {len(val_rows):,} val examples")
    return train_rows, val_rows


train_rows, val_rows = load_metadata(cfg.data_dir, smoke_test=cfg.smoke_test)


#  Cell 4: Build HuggingFace Dataset 
# %%
def rows_to_dataset(rows: list[dict]) -> Dataset:
    return Dataset.from_dict({
        "audio":      [r["audio_path"] for r in rows],
        "transcript": [r["transcript"] for r in rows],
    }).cast_column("audio", Audio(sampling_rate=16_000))


dataset = DatasetDict({
    "train": rows_to_dataset(train_rows),
    "test":  rows_to_dataset(val_rows),
})

print(dataset)


#  Cell 5: Load Whisper processor 
# %%
processor = WhisperProcessor.from_pretrained(
    cfg.base_model,
    language = cfg.language,
    task     = cfg.task,
)
print(f"Processor loaded: {cfg.base_model}")


#  Cell 6: Feature extraction 
# %%
def prepare_dataset(batch: dict) -> dict:
    """
    Convert raw audio → log-mel spectrogram + tokenized labels.
    Called per-example by Dataset.map().
    """
    audio = batch["audio"]
    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate = audio["sampling_rate"],
    ).input_features[0]

    batch["labels"] = processor.tokenizer(batch["transcript"]).input_ids
    return batch


dataset = dataset.map(
    prepare_dataset,
    remove_columns = dataset.column_names["train"],
    num_proc       = 1,
    desc           = "Extracting features",
)

print("Feature extraction complete.")


#  Cell 7: Data collator 
# %%
@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: WhisperProcessor

    def __call__(self, features: list[dict]) -> dict:
        # Pad input features
        input_features = [{"input_features": f["input_features"]} for f in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        # Pad labels
        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch   = self.processor.tokenizer.pad(label_features, return_tensors="pt")

        # Replace padding token id with -100 (ignored in loss)
        labels = labels_batch["input_ids"].masked_fill(
            labels_batch.attention_mask.ne(1), -100
        )

        # Remove BOS token if prepended
        if (labels[:, 0] == self.processor.tokenizer.bos_token_id).all():
            labels = labels[:, 1:]

        batch["labels"] = labels
        return batch


data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)
print("Data collator ready.")


#  Cell 8: Metrics 
# %%
wer_metric = evaluate.load("wer")


def compute_metrics(pred) -> dict:
    pred_ids    = pred.predictions
    label_ids   = pred.label_ids

    # Replace -100 with pad_token_id so we can decode
    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str  = processor.tokenizer.batch_decode(pred_ids,  skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * wer_metric.compute(predictions=pred_str, references=label_str)
    return {"wer": wer}


print("WER metric loaded.")


#  Cell 9: Load Whisper model 
# %%
model = WhisperForConditionalGeneration.from_pretrained(cfg.base_model)

# Disable cache — saves memory during training
model.config.use_cache = False

# Force the model to decode in English
model.config.forced_decoder_ids   = None
model.config.suppress_tokens      = []
model.generation_config.language  = cfg.language
model.generation_config.task      = cfg.task
model.generation_config.forced_decoder_ids = None

if cfg.gradient_checkpointing:
    model.enable_input_require_grads()

n_params = sum(p.numel() for p in model.parameters()) / 1e6
print(f"Model: {cfg.base_model} ({n_params:.1f}M parameters)")


#  Cell 10: Training arguments 
# %%
max_steps = 20 if cfg.smoke_test else cfg.max_steps

training_args = Seq2SeqTrainingArguments(
    output_dir                   = cfg.output_dir,
    per_device_train_batch_size  = 2 if cfg.smoke_test else cfg.per_device_train_batch_size,
    per_device_eval_batch_size   = 2 if cfg.smoke_test else cfg.per_device_eval_batch_size,
    gradient_accumulation_steps  = 1,
    learning_rate                = cfg.learning_rate,
    warmup_steps                 = min(cfg.warmup_steps, max_steps // 4),
    max_steps                    = max_steps,
    gradient_checkpointing       = cfg.gradient_checkpointing,
    fp16                         = cfg.fp16,
    evaluation_strategy          = "steps",
    eval_steps                   = min(cfg.eval_steps, max_steps),
    save_strategy                = "steps",
    save_steps                   = min(cfg.save_steps, max_steps),
    logging_steps                = min(cfg.logging_steps, max_steps // 4),
    load_best_model_at_end       = True,
    metric_for_best_model        = "wer",
    greater_is_better            = False,
    push_to_hub                  = bool(cfg.hub_model),
    hub_model_id                 = cfg.hub_model or None,
    report_to                    = "none",
    predict_with_generate        = True,
    generation_max_length        = 225,
    remove_unused_columns        = False,
    label_names                  = ["labels"],
)

print(f"Training for {max_steps} steps")
print(f"FP16: {cfg.fp16} | Device: {'GPU' if cfg.fp16 else 'CPU'}")


#  Cell 11: Trainer 
# %%
trainer = Seq2SeqTrainer(
    model           = model,
    args            = training_args,
    train_dataset   = dataset["train"],
    eval_dataset    = dataset["test"],
    data_collator   = data_collator,
    compute_metrics = compute_metrics,
    tokenizer       = processor.feature_extractor,
)

print("Trainer ready. Starting fine-tuning...")
print("─" * 60)


#  Cell 12: Train 
# %%
trainer.train()
print("Training complete!")


#  Cell 13: Evaluate 
# %%
eval_results = trainer.evaluate()
print(f"\nFinal WER: {eval_results['eval_wer']:.2f}%")


#  Cell 14: Save locally 
# %%
local_save = Path(cfg.output_dir) / "final"
trainer.save_model(str(local_save))
processor.save_pretrained(str(local_save))
print(f"Model saved locally → {local_save}")


#  Cell 15: Push to HuggingFace Hub (optional) 
# %%
if cfg.hub_model:
    print(f"Pushing to HuggingFace Hub: {cfg.hub_model}")
    kwargs = {
        "dataset_tags":  "medical-speech",
        "model_name":    "Whisper Medical — Panacea",
        "language":      "en",
        "model_id":      cfg.hub_model,
        "tasks":         "automatic-speech-recognition",
        "tags":          ["medical", "whisper", "panacea", "hospital"],
    }
    trainer.push_to_hub(**kwargs)
    print(f"Model pushed! Load it with:")
    print(f"  model = WhisperModel('{cfg.hub_model}')")
else:
    print("Hub push skipped (cfg.hub_model not set).")
    print(f"\nTo load your fine-tuned model, update src/voice/stt.py:")
    print(f"  WHISPER_MODEL = '{local_save}'")


#  Cell 16: Quick inference test 
# %%
def transcribe_sample(audio_path: str) -> str:
    """Test the fine-tuned model on a single WAV file."""
    audio_array, sr = librosa.load(audio_path, sr=16_000)
    inputs = processor(audio_array, sampling_rate=sr, return_tensors="pt")
    with torch.no_grad():
        generated_ids = model.generate(inputs["input_features"])
    return processor.batch_decode(generated_ids, skip_special_tokens=True)[0]


# Demonstrate on first available eval example
sample_path = dataset["test"][0]["audio"]["path"] if len(dataset["test"]) > 0 else None
if sample_path and Path(sample_path).exists():
    pred = transcribe_sample(sample_path)
    ref  = val_rows[0]["transcript"] if val_rows else ""
    print(f"\nSample inference:")
    print(f"  Predicted : {pred}")
    print(f"  Reference : {ref}")


# CLI — run as plain script with --smoke-test flag

if __name__ == "__main__":
    import argparse, sys

    parser = argparse.ArgumentParser(description="Fine-tune Whisper on medical speech")
    parser.add_argument("--smoke-test", action="store_true",
                        help="Run 3-example test on CPU (no GPU needed)")
    parser.add_argument("--hub",        default="",
                        help="HuggingFace Hub model id to push after training")
    args = parser.parse_args()

    cfg.smoke_test = args.smoke_test
    cfg.hub_model  = args.hub

    # Re-run all cells in order (already executed above when imported as module)
    # This block is a no-op when run from CLI since cells run at import time.
    print("\nFine-tuning pipeline complete.")
    print(f"  WER: {eval_results.get('eval_wer', 'N/A'):.2f}%")
    print(f"  Saved: {local_save}")
